/* POSTS */
export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const FETCH_POSTS = "FETCH_POSTS";
export const UNIQUE_CATEGORIES = "UNIQUE_CATEGORIES";
export const INCLUDE_POST_BY_CATEGORY = "INCLUDE_POST_BY_CATEGORY";
export const MATCH_POST_BY_TITLE = "MATCH_POST_BY_TITLE";
export const FILTERED_POSTS = "FILTERED_POSTS";
export const UPDATE_SELECTED_JOB_POST_TITLE = "UPDATE_SELECTED_JOB_POST_TITLE";

/* TESTIMONIALS */
export const RECEIVE_TESTIMONIALS = "RECEIVE_TESTIMONIALS";
export const FETCH_TESTIMONIALS = "FETCH_TESTIMONIALS";
export const TESTIMONIALS = "TESTIMONIALS";
