/* POSTS */
export const RECEIVE_POSTS = "RECEIVE_JOBS";
export const UNIQUE_CATEGORIES = "UNIQUE_CATEGORIES";
export const INCLUDE_POST_BY_CATEGORY = "INCLUDE_POST_BY_CATEGORY";
export const FILTERED_POSTS = "FILTERED_POSTS";
export const FETCH_POSTS = "FETCH_JOBS";
