/* POSTS */
export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const FETCH_POSTS = "FETCH_POSTS";
export const UNIQUE_CATEGORIES = "UNIQUE_CATEGORIES";
export const INCLUDE_POST_BY_CATEGORY = "INCLUDE_POST_BY_CATEGORY";
export const MATCH_POST_BY_TITLE = "MATCH_POST_BY_TITLE";
export const FILTERED_POSTS = "FILTERED_POSTS";
export const UPDATE_SELECTED_POST_TITLE = "UPDATE_SELECTED_POST_TITLE";

/* TESTIMONIALS */
export const RECEIVE_TESTIMONIALS = "RECEIVE_TESTIMONIALS";
export const FETCH_TESTIMONIALS = "FETCH_TESTIMONIALS";
export const TESTIMONIALS = "TESTIMONIALS";

/* FACILITIES */
export const RECEIVE_FACILITIES = "RECEIVE_FACILITY";
export const FETCH_FACILITIES = "FETCH_FACILITY";
export const MATCH_FACILITY_BY_NAME = "MATCH_FACILITY_BY_NAME";
export const FILTERED_FACILITIES = "FILTERED_FACILITIES";
export const UPDATE_SELECTED_FACILITY_NAME = "UPDATE_SELECTED_FACILITY_NAME";

/* WEB LINKS */
export const RECEIVE_RESOURCES = "RECEIVE_RESOURCES";
export const FETCH_RESOURCES = "FETCH_RESOURCES";
export const RESOURCES = "RESOURCES";
